-- Ejecutar en Supabase: SQL Editor → New query → Run
-- Crea la tabla de gastos (equivalente a SQLite expenses) y políticas RLS mínimas para la anon key.
-- En producción con varios usuarios reemplaza estas políticas por auth + RLS por usuario/casa.

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  date text not null,
  category text not null,
  description text,
  amount double precision not null,
  tip double precision not null default 0,
  person text not null default 'Dafne Avila'
);

comment on table public.expenses is 'GastoFlow — gastos (fecha YYYY-MM-DD como texto, igual que SQLite)';

alter table public.expenses enable row level security;

drop policy if exists "expenses_anon_all" on public.expenses;
drop policy if exists "expenses_authenticated_all" on public.expenses;

-- Rol anon (clave publicable en la app): acceso total a la tabla. Solo para uso controlado / hogar.
-- Si el proyecto es público, usa autenticación Supabase y políticas por user_id.
create policy "expenses_anon_all"
  on public.expenses
  for all
  to anon
  using (true)
  with check (true);

create policy "expenses_authenticated_all"
  on public.expenses
  for all
  to authenticated
  using (true)
  with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.expenses to anon, authenticated;
